### ISSUE TITLE
Start plugin tools error

### ISSUE THREAD

**Issue by FahadMaqbool** [CyberReboot/vent#1004]
After adding and building plugin tools, when I start plugin tools, all tools fails to start/ below is my terminal. showing the error. 

┌ Start tools        ^T to toggle main ────────────────────────────────────────┐
│                                                                              │
│ Select w┌ Message ─────────────────────────────────────────────────┐         │
│         │                                                          │         │
│    Plugi│ cyberreboot-vent-plugins-kibana-master-HEAD: failed      │         │
│         │ cyberreboot-vent-plugins-grafana-master-HEAD: failed     │         │
│         │ cyberreboot-vent-plugins-replay-pcap-master-HEAD:        │         │
│         │ failed                                                   │         │
│         │ cyberreboot-vent-plugins-gpu-example-master-HEAD:        │         │
│         │ failed                                                   │         │
│         │ cyberreboot-vent-plugins-tcpdump-hex-parser-master-      │         │
│         │ - more -                                                 │         │
│         │                                                     OK   │         │
│         └──────────────────────────────────────────────────────────┘         │
│         [X]  dshell_netflow_parser:master:HEAD                               │
│         [X]  replay_pcap:master:HEAD                                         │
│                                                  

Other than that My vent is like this. 
┌ Vent v0.4.9.dev0     ^T for help    ^Q to quit    TAB to close menu popup ───┐
│                                                                              │
│ Date:           2018-03-07 11:45:38.412720 UTC                               │
│ Uptime:         11:45:38 up  7:21,  load average: 0.18, 0.15, 0.19           │
│ Logical CPUs:   4                                                            │
│ GPUs:           None                                                         │
│ User Data:      /root/.vent                                                  │
│ File Drop:      /opt/vent_files                                              │
│ Containers:     0 running                                                    │
│ Status:         Idle                                                         │
│ Core Tools:     0/9 running, 13/9 built, 9/9 installed                       │
│ Plugin Tools:   0/21 running, 13/18 built (3 custom), 4/18 installed (3 cu   │
│ Jobs:           0 jobs running (0 tool containers), 0 completed jobs         │
│                                                                              │
│                                                                              │
│                                                                              │
│                                                                              │
│                                                                              │
│                                                                              │
│                                                                              │
│                                                                              │
│                                                                              │
│                                                                              │
└ ^X: Menu ────────────────────────────────────────────────────────────────────┘

**Comment by cglewis** [comment]
can you provide the log file for this? it's located at `/root/.vent/vent.log`

**Comment by FahadMaqbool** [comment]
Actually, there was no log file generated. As per my understanding rabbitmq was already running on my PC When i removed rabbitmq and started vent. it successfully built and started all tools.

**Comment by cglewis** [comment]
ok, glad you got it working.
