### ISSUE TITLE
rmq-es-connector should be smarter about datatypes before putting into ES

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#110]

**Comment by Joecakes4u** [comment]
https://github.com/CyberReboot/vent/blob/master/core/rmq-es-connector/rmq_es_connector.py#L50

Is it possible to combine all the logic for assigning index name to be:
```
index = method.routing_key.split(".")[0]
```
making that code more generic? 

Or is the original assignment (`index = "pcap"`) more important?

**Comment by cglewis** [comment]
no, that's a good idea.
