### ISSUE TITLE
Starting 'All' containers multiple times will start collectors by default.

### ISSUE THREAD

**Issue by Joecakes4u** [CyberReboot/vent#154]
Even if active and passive collectors are not configured in the `local-collection` section of `core.template`, they are turned on after enough tries running `Start All` in menu or via template_parser.py call.

**Comment by cprafullchandra** [comment]
@Joecakes4u Any idea how many tries? Is it just more than 1?

**Comment by Joecakes4u** [comment]
At least two, haven't confirmed if this is still a problem after closing #92

**Comment by Joecakes4u** [comment]
I tried to reproduce this bug on a new Vent instance, and it did not display this behavior. It ran as expected.

Closing this issue for now.

**Comment by Joecakes4u** [comment]
Recreated this behavior.

I configured them to turn on, then commented out the `active = off` and `passive = off` options in `core.template`. After configuration, the intended behavior is that they are by default off, since there is nothing explicitly telling them to turn on. However, both active and passive collectors are running.
