### ISSUE TITLE
Starting `core` the first time doesn't start all the cores.

### ISSUE THREAD

**Issue by Joecakes4u** [CyberReboot/vent#167]
When starting `core`, I have to start them three or four times before they all start. The most common core that fails to start the first time is `rq-worker`.

**Comment by cprafullchandra** [comment]
@Joecakes4u I think this might have to do with `vent-management` not starting correctly at first boot. Have you confirmed whether `vent-management` is running or not when you `start Cores`?

**Comment by Joecakes4u** [comment]
Yeah it was on when I tried this.

**Comment by cglewis** [comment]
wasn't able to reproduce, more details?

**Comment by Joecakes4u** [comment]
I wasn't able to reproduce this either. May have been patched, or I may not have waited the appropriate time for the cores to start. Sometimes  `rq-worker` won't start properly (though very rarely), and an error message will pop up mentioning `core-aaa-redis` not being on yet. haven't been able to reproduce that consistently, so I will close this issue for now until that specific issue pops up again.
