### ISSUE TITLE
Make Elasticsearch indices smarter, configurable.

### ISSUE THREAD

**Issue by Joecakes4u** [CyberReboot/vent#168]
Elasticsearch indices are currently based on plugin name, but it is possible to configure them.

**Comment by Joecakes4u** [comment]
line 56 of `vent/core/rmq_es_connector/rmq_es_connector.py` seems relevant to this issue, if I'm not mistaken.
```
def callback(self, ch, method, properties, body):
        """
        callback triggered on rabiitmq message received and sends it to
        an elasticsearch index
        """
        # !! TODO index needs to be reworked for multiple file types
        index = method.routing_key.split(".")[0]
```

Is it possible to look at templates from `rmq_es_connector`'s perspective, or are template files invisible to that container?

**Comment by cglewis** [comment]
yes, that is relevant. currently `rmq-es-connector` doesn't have access to the templates, but you can add that by modifying `core.template` and adding `"Binds": ["/var/lib/docker/data/templates:/templates:ro"]` to the `HostConfig` for `rmq-es-connector` like `template-change` has.

**Comment by Joecakes4u** [comment]
`method.routing_key.split(".")[0]` is actually the name of an individual plugin, not a namespace. 
(ex: in `vent-plugins`,  `method.routing_key.split(".")[0]` == "csv_row_broadcast")

So it is not very useful since templates are namespace-specific. One work-around could be to use `modes.template` to configure individual plugins instead of the plugin's namespace's template 
(ex: in `vent-plugins`, configure `mode.template` instead of `csv.template`).
