### ISSUE TITLE
Updating/Removing plugins error: permission denied

### ISSUE THREAD

**Issue by Joecakes4u** [CyberReboot/vent#182]
I get this message:
`sh: /var/lib/docker/data/: Permission denied`

Seems to be blocking a lot of progress so I'll work on this first.

**Comment by Joecakes4u** [comment]
In `custom` script, `chmod -R 777 /var/lib/docker/data` doesn't exist. Is this intended?

**Comment by cglewis** [comment]
It was probably overlooked.
