### ISSUE TITLE
Cores are starting, stay on for a few seconds, then are automatically deleted

### ISSUE THREAD

**Issue by Joecakes4u** [CyberReboot/vent#184]
Steps I used to reproduce:

1. Create a vent instance
2. Add plugin: https://github.com/Joecakes4u/vent-jek
3. If running on Virtualbox: 
  - Modes -> Configure -> core.template
  - Uncomment `public_nic = eth1` 
  - Hit `ctrl+s` and `ctrl+q` to save and quit from the text editor
4. Modes -> Start `All`

To see this in action:

1. After Starting `All`, quickly navigate to vent's shell
2. Run `docker ps` a few times
3. Cores should exist at first, then will disappear from the list of running containers. Even after running `docker ps -a`, they don't exist in any other state (e.g. Exited, Restarting). Seems they are just gone.

**Comment by cglewis** [comment]
I would have a look under `docker logs vent-management` and see if anything look odd there.

**Comment by Joecakes4u** [comment]
Things look normal, nothing but HostConfigs, environment variables, etc. that you would normally see.

**Comment by Joecakes4u** [comment]
Elasticsearch spit this out:
`unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade`

I'll try to make a new ISO and see if that fixes this.

**Comment by cglewis** [comment]
Looks like this might be related: https://discuss.elastic.co/t/elasticsearch-warn-unable-to-install-syscall-filter/42819

**Comment by cglewis** [comment]
looks like only `rq-worker` containers exit for me. not sure why yet.

**Comment by cglewis** [comment]
@Joecakes4u looks like another way this might occur is if vent is running with virtualbox and you leave the `public_nic = eth1` commented out in `core.template`, since virtualbox use's `eth1` by default, rather than `eth0`
