### ISSUE TITLE
logs menu seems to be broken with namespaces

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#195]

**Comment by cprafullchandra** [comment]
![screen shot 2016-09-27 at 7 44 48 pm](https://cloud.githubusercontent.com/assets/6751560/18899050/f42c59ec-84ea-11e6-9053-b1a3f5173a3a.png)

**Comment by cprafullchandra** [comment]
Looks like the namespaces are due to multiple copies of the container: one from `cyberreboot/` and the other from `core/`
