### ISSUE TITLE
update elasticsearch to 5

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#234]

**Comment by Joecakes4u** [comment]
https://github.com/mobz/elasticsearch-head#running-with-built-in-server
```
– for Elasticsearch 5.x:
site plugins are not supported. Run elasticsearch-head as a standalone server
```

Running as a standalone comes with a security risk. 
"your cluster is open to cross origin from anywhere."

**Comment by cglewis** [comment]
check out this setup and see if we can use something similar: https://hub.docker.com/r/blacktop/elastic-stack/

**Comment by cglewis** [comment]
es5 is not stable, so leaving at es2 for now.
