### ISSUE TITLE
have a reset option

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#408]
should remove `~/.vent` and all images and containers built by vent.

**Comment by lilchurro** [comment]
<img width="790" alt="screen shot 2017-05-18 at 5 27 41 pm" src="https://cloud.githubusercontent.com/assets/24439710/26224273/7155be34-3bd6-11e7-9167-0976ee4a2915.png">
Going to implement the reset option in the menu.

**Comment by cglewis** [comment]
@lilchurro there's a couple helper functions that will help getting the images and containers for this:

`vent.helpers.meta.Containers`
`vent.helpers.meta.Images`
