### ISSUE TITLE
Inconsistent use of switchForm versus change_forms

### ISSUE THREAD

**Issue by cprafullchandra** [CyberReboot/vent#431]
One resets user history, the other does not. Which do we want to keep, or standardize, and when do we want to use the other?

**Comment by cprafullchandra** [comment]
@cglewis Anything thoughts on resetting of history. If not, then I think we may want to remove the change_form in `menu.py`.

**Comment by cglewis** [comment]
I think @lilchurro had some ideas around a menu class that would clean this problem up

**Comment by cglewis** [comment]
FYI, I created a class for the tutorial menus that show that we should be able to do the same thing for the rest of the menu code to make things a lot cleaner and have less duplication/inconsistencies.
