### ISSUE TITLE
switchForm(None) can create circular loops & cause issues when the starting form is changed

### ISSUE THREAD

**Issue by cprafullchandra** [CyberReboot/vent#432]

**Comment by cglewis** [comment]
`switchForm(None)` is intended to quit the program. what issues are you seeing?

**Comment by cprafullchandra** [comment]
What happens is that with Tutorial set as the new beginning, if I quit the tutorial and go to the main menu, and then navigate to Start Tools and then click CANCEL, it goes back to tutorial. And when I try to quit the tutorial it goes back to the main menu. And when I then quit the main menu it goes back to tutorial. And the user then gets stuck in an infinite loop. switchForm(None), which was originally in all the tool manipulation functions doesn't seem to actually quit the application but default to previous page. That's my theory.

**Comment by cglewis** [comment]
interesting.  i think with the comment about reseting the parentApp variable in the PR #433 this should be fine to get rid of all of the `None` form switches.

**Comment by cglewis** [comment]
I think I resolved the circular issue with adding an `else` that sets to the main form if not tutorial. @cprafullchandra can this be closed?

**Comment by cprafullchandra** [comment]
@cglewis still able to reproduce using the flow described above.

**Comment by cglewis** [comment]
I think this is related to the very first session when leaving the tutorial, but not vent. subsequent sessions of vent after the tutorial has been seen and `vent.init` has been created don't appear to have this problem for me.

**Comment by cglewis** [comment]
i believe this is resolved now, also squashed an issue where ctrl-q wouldn't quit.  please reopen if this is still an issue
