### ISSUE TITLE
When building cores, if you uncheck one, vent still builds it anyways

### ISSUE THREAD

**Issue by bpagon13** [CyberReboot/vent#651]

**Comment by Jeff-Wang93** [comment]
I think this bug also applies for removing. If you remove 1, all get removed.

**Comment by cglewis** [comment]
this might be a bigger issue, going to bump to the next release.

**Comment by bpagon13** [comment]
Can't reproduce this issue

**Comment by cglewis** [comment]
Will do some more testing to try to reproduce, if I can't then I'll close

**Comment by cglewis** [comment]
build looks correct, but remove doesn't as @Jeff-Wang93 mentions.  I'll open a new issue for that.
