### ISSUE TITLE
When adding/building plugins from a custom repo, everything has to be lower case

### ISSUE THREAD

**Issue by Jeff-Wang93** [CyberReboot/vent#672]
`Jeff-Wang93-vent-plugins-grafana-master:d2209cf17d27ef26e97ee0e79fa2929f79140ac8` (Bad)
`jeff-wang93-vent-plugins-grafana-master:d2209cf17d27ef26e97ee0e79fa2929f79140ac8` (Good)

File paths also need to be lowercased:
eg: `jeff-wang93-vent-plugins-GRafAna-master` is bad

**Comment by cglewis** [comment]
not this will also require file paths within the repo to be lowercased

**Comment by cglewis** [comment]
if the directory containing the Dockerfile has a capital letter, this will still have the same problem, I believe.
