### ISSUE TITLE
Template's add_option() doesn't add additional options if a section already exists

### ISSUE THREAD

**Issue by lilchurro** [CyberReboot/vent#789]
When I tried to create a second option item under an existing section **[main]**, the second item is never added to the config file due to a bug in add_option() wherein the function returns an error and the section is left unchanged because **[main]** as a section already exists.

**Comment by lilchurro** [comment]
Hrmm. Not sure why it created #790 when I referenced #789 in my PR. :\ oops.

**Comment by cglewis** [comment]
@lilchurro PR's get their own numbers that are on the same counter as issues, so you did it right, it just looks weird because they were created right next to each other.
