### ISSUE TITLE
syntax error @ prep_start()

### ISSUE THREAD

**Issue by lilchurro** [CyberReboot/vent#794]
I ran a fresh install of Vent, and just finished installing and building core tools. When trying to start them, however, it hit this error. (Triggered at vent/api/plugin_helpers.py, line 571)

```
2017-08-17 12:33:03,097 - vent.api.plugin_helpers - ERROR - prep_start failed with error: local vari
able 'status' referenced before assignment
```

**Comment by cglewis** [comment]
`status` is defined at the beginning of the function, not sure how it could be referenced before assignment there.  Will try to reproduce.

**Comment by cglewis** [comment]
I just did a fresh install and started the core tools without error and am unable to reproduce.  Can you provide more context for reproducing?

**Comment by cglewis** [comment]
@lilchurro I believe this was resolved with https://github.com/CyberReboot/vent/pull/816, no?

**Comment by lilchurro** [comment]
Yep. Closing ticket.
