### ISSUE TITLE
reset does not always cleanly remove everything

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#818]
<img width="338" alt="screen shot 2017-08-23 at 1 25 30 pm" src="https://user-images.githubusercontent.com/2931079/29629390-9c23669e-8806-11e7-8d69-be1920f49a39.png">

**Comment by Jeff-Wang93** [comment]
I think this happens when two images have the same image ID. So Vent deletes by image id, which is stored in a list. If two different images with the same ID are to be deleted, you'll get that error message.
