### ISSUE TITLE
git checkout errors out the first time when adding core tools

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#819]
```
2017-08-23 14:31:30,002 - vent.api.plugin_helpers - ERROR - checkout failed with error: Command '['git', 'checkout', 'master']' returned non-zero exit status 128
```

**Comment by cglewis** [comment]
Appears the issue is somehow the clone function is returning `True` that it successfully cloned, but it didn't actually clone the repository

**Comment by lilchurro** [comment]
Fixed in my fork's feature/586 branch, but now inventory and start core plugins don't work. T_T

**Comment by cglewis** [comment]
No longer an issue with the rewrite
