### ISSUE TITLE
restful interface to the API

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#823]

**Comment by rashley-iqt** [comment]
Is the idea here just a set of RESTful endpoints to the api/actions framework?  Also, are there any thoughts on how to handle auth?

**Comment by cglewis** [comment]
yeah, exactly.

auth is a good question - do you have suggestions?

**Comment by cglewis** [comment]
yeah, i tend to agree with both of those points.  not sure exactly what those should be, open to proposed paths here though.

**Comment by rashley-iqt** [comment]
I'm going to do some research on this one.

**Comment by rashley-iqt** [comment]
http://docs.python-requests.org/en/master/user/authentication/

It looks like we can use the requests library and use OAuth2.  That is fairly standard and it should let people plug in their preferred provider under the hood.

**Comment by cglewis** [comment]
Yeah, I’m good with going the OAuth2 direction.

**Comment by cglewis** [comment]
closing as no new activity in over a year.
