### ISSUE TITLE
Allow user to put comments in when configuring a tool

### ISSUE THREAD

**Issue by bpagon13** [CyberReboot/vent#829]

**Comment by cglewis** [comment]
@bpagon13 doesn't this already work if they start the line with a `#`?

**Comment by bpagon13** [comment]
It does work in the sense that vent doesn't evaluate it at all when saving or pulling up configurations. However, any comments that are made are not pulled up and shown when a user is trying to configure a tool. This could be a pain if a user comments something out to try something out, and then when they go back in to uncomment it, it's not there anymore.

**Comment by cglewis** [comment]
ah, good point.
