### ISSUE TITLE
add an extra 'metadata' field for network_tap to be stored in redis

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#874]
- `vent/core/network_tap/ncontrol/rest/create.py` needs to have an optional parameter in the payload for `metadata` which will be a JSON object.
- the `metadata` field needs to then be stored as hash in redis where the key is the `id` parameter of the payload

**Comment by rosemilk** [comment]
@cglewis I'd like to help with this. How do I begin? Thanks.

**Comment by cglewis** [comment]
@rosemilk excellent!

So, first I'd take a look at `vent/core/network_tap/ncontrol/rest/create.py` and look at the other payload params that are coming in to the `POST` function, such as `id` and `iters` (there's like 5).  This issue needs an additional one added named `metadata` that expects a JSON object.  Since there is already a connection made to Redis in the function, all you need to do is set a new hash using that Redis connection where the key to the hash is `id` param also coming in to that same function and value is the key/value pairs of the json object of `metadata`.

For testing, you'll want to have docker available.  Run the redis container:
```
docker run --name redis -d redis redis-server --appendonly yes
```
Then build and run the `ncontrol` container.  Go into the ncontrol directory then do:
```
docker build -t ncontrol .
docker run -d -p 8080:8080 --link redis:redis ncontrol
```
Once that's up and running, make a POST request to http://localhost:8080/create with the payload that's expected.

Feel free to reach out with more questions or if you get stuck.

**Comment by cglewis** [comment]
@rosemilk this has become critical path for another project, and didn't see any activity on it from you, so taking care of this one.
