### ISSUE TITLE
add scripts into path with a common naming scheme for auto-complete

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#88]
need to note the list of scripts to include, and minimally a help output when running them for usage examples

**Comment by Joecakes4u** [comment]
Scripts in info_tools
- [ ] get_info.sh
- [ ] get_logs.py
- [ ] get_messages.sh
- [ ] get_namespaces.py
- [ ] get_service.sh
- [ ] get_status.py
- [ ] get-tasks.sh
- [ ] get_tools.sh
- [ ] get_types.sh
