### ISSUE TITLE
new vent logo needs to be added to the readme

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#888]
under `docs`, the vent logo should be added into a folder called `img` and added to the main README.md page.  the logo can be found here: https://blog.cyberreboot.org/hacktoberfest-is-upon-us-a8ff56a9d724

**Comment by jamesday7** [comment]
I'm just about to create a push request :)

**Comment by jamesday7** [comment]
@cglewis is it to replace the fork image?

**Comment by DonutDeflector** [comment]
I'll do it in about an hour. Cheers!

**Comment by cglewis** [comment]
@jamesday7 yes, the ascii art one can be removed in place of the logo
