### ISSUE TITLE
update on core tools appears to be broken

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#914]

**Comment by nitinkgp23** [comment]
Can you please elaborate on this?

**Comment by cglewis** [comment]
after core tools have been `added`/`built`/`started` if a new version exists of the core tool (from a new commit) and then go do an `update` from the menu it does not behave as expected (stop current running selected cores to update, rebuild, and restart.

**Comment by cglewis** [comment]
No longer an issue with the rewrite
