### ISSUE TITLE
Stopping All Containers & Starting All Containers starts new containers instead of restarting old containers

### ISSUE THREAD

**Issue by cprafullchandra** [CyberReboot/vent#92]

**Comment by cglewis** [comment]
only true for non-core things, correct?

**Comment by cprafullchandra** [comment]
@cglewis Correct!

**Comment by Joecakes4u** [comment]
Is this the intended behavior, and we just haven't been cleaning up unused non-core containers, or is the intended behavior to restart stopped non-core containers?

**Comment by cprafullchandra** [comment]
The intended behavior is to restart old containers rather than create new containers and leaving unused old containers until clean.
