### ISSUE TITLE
Number of installed core plugins still corruptible.

### ISSUE THREAD

**Issue by lilchurro** [CyberReboot/vent#920]
<img width="489" alt="screen shot 2017-10-20 at 4 36 41 pm" src="https://user-images.githubusercontent.com/24439710/31841550-f9d1af74-b5b7-11e7-98e5-c1d76f367dc0.png">

There still seems to be an issue with obtaining the accurate count of core tools installed. (See screenshot.)

**Comment by Jeff-Wang93** [comment]
In the `plugin_manifest.cfg`, are there multiple, duplicate entries of plugins?

**Comment by lilchurro** [comment]
There are entries from both the experimental and the master branches. This is fine, but the total count should probably be updated (i.e., 17/17 or something...)

**Comment by cglewis** [comment]
hmm, so the 9 is what "expected" maybe if there's also experimental added or some other thing those should be counted separately?

**Comment by lilchurro** [comment]
Not sure what the best way to handle it is, but that sounds usable. Or should experimental ones be considered regular plugins?

**Comment by cglewis** [comment]
No longer valid with the rewrite
