### ISSUE TITLE
ImportError: No module named 'Queue'

### ISSUE THREAD

**Issue by gokulsoumya** [CyberReboot/vent#988]
I installed vent in a virtualenv using `pip3 install vent` and ran `vent`. This is the output that I got:

```
Traceback (most recent call last):
  File "/mnt/0b6b53eb-f83a-4f34-9224-da2310643534/Projects/virtual/vent/bin/vent", line 6, in <module>
    from vent.menu import VentApp
  File "/mnt/0b6b53eb-f83a-4f34-9224-da2310643534/Projects/virtual/vent/lib/python3.5/site-packages/vent/menu.py", line 10, in <module>
    from vent.api.actions import Action
  File "/mnt/0b6b53eb-f83a-4f34-9224-da2310643534/Projects/virtual/vent/lib/python3.5/site-packages/vent/api/actions.py", line 1, in <module>
    import Queue
ImportError: No module named 'Queue'
```

**Comment by cglewis** [comment]
python3 is not yet supported, see #194

**Comment by gokulsoumya** [comment]
Will Python3 be supported soon ?

**Comment by cglewis** [comment]
It hasn't been a priority at this point.  Vent can be run from a Docker container though so it doesn't muck with environments that may or may not have particular requirements such as python2 or python3 or specific versions of libraries.  Does that not work in your environment?  I'm happy to move it up the priority list if it's preventing you from using Vent.

**Comment by gokulsoumya** [comment]
I was looking for a project to contribute to, and I stumbled upon yours. You use `npyscreen` ([I made an app with it](https://github.com/gokulsoumya/clid)), so I was trying to familiarize myself with the codebase :)

**Comment by cglewis** [comment]
Gotcha, very cool. 

I'd welcome contributions - especially if you want to start tackling making it work with python3 👍
